[dependencies]
array = "https://github.com/aviate-labs/array.mo#v0.2.0"
base = "https://github.com/dfinity/motoko-base#moc-0.7.4"
itertools = "0.1.1"

[package]
name = "account"
version = "1.0.0"
description = "A Motoko implementation of ICRC-1 and ICRC-7 Accounts."
repository = "https://github.com/letmejustputthishere/account"
keywords = [ "account", "icrc", "icrc1", "icrc7", "icrc-1", "icrc-7" ]
license = "MIT"

[dev-dependencies]
test = "1.1.1"